### ISSUE TITLE
Configurable route on dockerfile

### ISSUE THREAD

**Issue by ericwooley** [peers/peerjs-server#213]
### I have a suggestion:
I am setting up a peerjs server, and am planning to use the docker image. However, /myApp isn't a good route choice for me. It would be nice to set that with an environment variable. As it is now I need to over ride the entry point.

**Comment by NitroLine** [comment]
You can change this by changing  `--path ` param  in CLI using docker-compose command
You can also add a SSL to your server.
```yml
version: '3.7'

services:
  peerjs:
    image: peerjs/peerjs-server
    command: node bin/peerjs --port 9000 --path /your_path_here --cors --sslkey /var/ssl/privkey.pem --sslcert /var/ssl/fullchain.pem
    container_name: peerjs_server
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/certs:/var/ssl
```
